export const tramposData = [
    {
        what:'Simulação mostra quais crianças são adotadas (e quais não são) no Brasil',
        where:'Estadão',
        link:'https://arte.estadao.com.br/brasil/adocao/criancas/',
        when:'2019',
        image:'https://media.newyorker.com/photos/5e8e4cb4f891bc0008babb16/master/w_2560%2Cc_limit/TNYI-Fran_Lebowitz.jpg',
        awards:'',
    },
    {
        what:'Encontre coworkings: listamos 247 na cidade de SP',
        where:'Estadão',
        link:'https://arte.estadao.com.br/pme/coworkings/',
        when:'2019',
        image:'',
        awards:'',
    },
    {
        what:'Alagamentos nos quatro primeiros meses de 2019 sobem 65% em São Paulo',
        where:'Estadão',
        link:'https://arte.estadao.com.br/sao-paulo/10-anos-de-chuvas/',
        when:'2020',
        image:'',
        awards:'',
    },
    {
        what:'Ritmo de festa: o segredo do hit de carnaval',
        where:'Estadão',
        link:'https://arte.estadao.com.br/cultura/carnaval/hits-carnaval-2020/',
        when:'2020',
        image:'',
        awards:'',
    },
    {
        what:'O que preciso saber antes de alugar um imóvel?',
        where:'Estadão',
        link:'https://arte.estadao.com.br/economia/aluguel/quiz-aluguel/',
        when:'2019',
        image:'',
        awards:'',
    },
    {
        what:'Os 100 artistas de maior sucesso do funk brasileiro na última década',
        where:'Estadão',
        link:'https://www.estadao.com.br/infograficos/cultura,os-100-artistas-de-maior-sucesso-do-funk-brasileiro-na-ultima-decada,1069703',
        when:'2020',
        image:'',
        awards:'',
    },
    {
        what:'Evite o desperdício: descubra como prolongar a validade dos alimentos em casa',
        where:'Estadão',
        link:'https://www.estadao.com.br/infograficos/saude,evite-o-desperdicio-descubra-como-prolongar-a-validade-dos-alimentos-em-casa,1089709',
        when:'2020',
        image:'',
        awards:'',
    },
    {
        what:'Reabertura em SP: veja fases da quarentena em casa cidade',
        where:'Estadão',
        link:'https://www.estadao.com.br/infograficos/saude,reabertura-em-sp-veja-fases-da-quarentena-em-cada-cidade,1099008',
        when:'2020',
        image:'',
        awards:'',
    },
    {
        what:'Brasil supera 1 milhão de casos',
        where:'Estadão',
        link:'https://www.estadao.com.br/infograficos/saude,brasil-supera-1-milhao-de-casos-de-covid-19,1101828',
        when:'2020',
        image:'',
        awards:'',
    },
    {
        what:'Qual o destino de R$ 1,2 bilhão de emendas de vereadores de São Paulo nos últimos 10 anos',
        where:'Estadão',
        link:'https://www.estadao.com.br/infograficos/politica,qual-o-destino-de-r-1-2-bilhao-de-emendas-de-vereadores-de-sao-paulo-nos-ultimos-10-anos,1115949',
        when:'2020',
        image:'',
        awards:'',
    },
    {
        what:'Mapas de apuração - Covas e Boulos disputam segundo turno; veja como cada bairro votou',
        where:'Estadão',
        link:'https://www.estadao.com.br/infograficos/politica,apuracao-mapas-prefeitura-sp-eleicoes-2020,1135463',
        when:'2020',
        image:'',
        awards:'',
    },
    {
        what:'Veja o perfil dos partidos para 2021 na Câmara Municipal',
        where:'Estadão',
        link:'https://www.estadao.com.br/infograficos/politica,psdb-sofre-leve-queda-pt-se-estabiliza-e-psol-avanca-na-camara-municipal-veja-o-perfil-dos-partidos-para-2021,1135749',
        when:'2020',
        image:'',
        awards:'',
    },
    {
        what:'MDB, PSDB e PSD elegeram mais prefeitos em cidades com maior IDHM',
        where:'Estadão',
        link:'https://www.estadao.com.br/infograficos/politica,mdb-psdb-e-psd-elegeram-mais-prefeitos-em-cidades-com-maior-idhm,1137248',
        when:'2020',
        image:'',
        awards:'',
    },
    {
        what:'Quiz: qual o perfil do colega de trabalho perfeito?',
        where:'Estadão',
        link:'https://www.estadao.com.br/infograficos/economia,quiz-qual-seu-colega-de-trabalho-perfeito,1130965',
        when:'2020',
        image:'',
        awards:'',
    },
    {
        what:'Coopertires',
        where:'Newton agência',
        link:'http://coopertires.com.br/',
        when:'2019',
        image:'',
        awards:'',
    }
];